chore(infrastructure): Remove retry limit for parallel executions on CBT
### How to test

```bash
export CBT_USERNAME='...'
export CBT_AUTHKEY='...'
export MDC_GCLOUD_SERVICE_ACCOUNT_KEY_FILE_PATH='...'
```

Open two or more terminals and run the tests in both terminals at the same time:

```bash
npm run screenshot:test
```

### What it does

CBT allows us to test up to 5 pages concurrently.

If two developers run their tests at the same time, we hit that limit:

```
Parallel execution limit reached - waiting for 5 seconds before retrying...
```

Currently, the tests will fail after 5 failed retry attempts:

```
Error: Capture request failed after 5 retry attempts - https://storage.googleapis.com/mdc-web-screenshot-tests/advorak/2018/05/24/16_43_43_944/704147ef0/mdc-button/classes/dense.html
    at sendCaptureRequest (/Users/advorak/dev/mdc-web/test/screenshot/lib/screenshot.js:77:11)
    at cbtApi.sendCaptureRequest.catch (/Users/advorak/dev/mdc-web/test/screenshot/lib/screenshot.js:88:16)
    at <anonymous>
```

This is to prevent infinite loops on requests that we know are going to keep failing, like HTTP 500 server errors.

However, it probably doesn't make sense to limit parallel executions to 5 retry attempts, because eventually the other developers' tests will finish and your tests will get a chance to run.

So this PR just removes the retry limit for parallel executions (but leaves all other retry limits intact).