chore: Fix broken TypeScript rewrite script (#4398)
This PR fixes the following error when running
`node scripts/rewrite-declaration-statements-for-typescript.js ~/dev/mdc/packages`:

```
[rewrite] packages/mdc-checkbox/constants.ts

node_modules/@babel/parser/lib/index.js:3843
    throw err;
    ^

SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (56:29)
    at Object.raise (node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.expectPlugin (node_modules/@babel/parser/lib/index.js:5148:18)
    at Object.parseClassProperty (node_modules/@babel/parser/lib/index.js:8229:12)
    at Object.parseClassProperty (node_modules/@babel/parser/lib/index.js:10260:18)
    at Object.pushClassProperty (node_modules/@babel/parser/lib/index.js:8193:30)
    at Object.parseClassMemberWithIsStatic (node_modules/@babel/parser/lib/index.js:8132:14)
    at Object.parseClassMemberWithIsStatic (node_modules/@babel/parser/lib/index.js:10166:11)
    at Object.parseClassMember (node_modules/@babel/parser/lib/index.js:8069:10)
    at Object.parseClassMember (node_modules/@babel/parser/lib/index.js:10123:11)
    at withTopicForbiddingContext (node_modules/@babel/parser/lib/index.js:8024:14)
```

This PR also:

* No longer rewrites `@material/foo` imports (they can be resolved as-is)
* Renames some variables for clarity
* Prints a more helpful error message when no arguments are passed to the script
* Fixes some unrelated Sass stylelint errors
* Updates GitHub API to use non-deprecated authentication method